### ISSUE TITLE
Would work on Windows 10 ARM?

### ISSUE THREAD

**Issue by mms-** [vividos/RemotePhotoTool#1]
What would it take to compile this, just the gphoto2 lib to be usable on Windows ARM platforms like Win IoT Core? Any help in the right direction would be appreciated!

**Comment by vividos** [comment]
Hi, no sorry, the project is x86 only, so it won't work on an ARM processor. You may have better luck porting libgphoto2 and gphoto2 to ARM processor, maybe by cross-compiling using MinGW and gcc or clang. Sorry!
