### ISSUE TITLE
Release always captures to same file

### ISSUE THREAD

**Issue by adamish** [vividos/RemotePhotoTool#2]
I'd really like to use this application for some stop gap animation, however every time I press release it saves to the same file e.g. C:\Users\adam\Pictures\2019-03-05\IMG_0001.jpg

Is there anyway to configure it to save to incrementing filename, i.e. IMG_0002.jpg, IMG_0003.jpg etc..

**Comment by vividos** [comment]
I just tried with version 1.5.0, and it worked for me. When I set the "Save to" format to "PC only", it begins at IMG_0001.jpg and advances the images one by one. If I use "Save to both", I get the same filenames of the Canon camera, starting with the image number the camera was last used to shoot.
