### ISSUE TITLE
Work with two cameras simultaneously?

### ISSUE THREAD

**Issue by fujie317** [vividos/RemotePhotoTool#3]
Does this program work with more one camera connected to a PC (Windows 7) via USB simultaneously? Also, what usb Windows driver needs to be installed for the cameras? I tried to use two cameras (Sony A6300 and Canon D60) with libgphoto2. Apparently, libgphoto2 talks to cameras via the Windows usb drivers. libusb-win32 did not work. libusbK works but only one camera at a time. Does your program work with more than one camera simultaneously?  I noticed your program includes a libusb.dll. Does that bypass the system driver?

**Comment by vividos** [comment]
Sorry, working with multiple cameras doesn't work. Only the Canon camera might work, as it uses the Canon SDK exclusively. No windows drivers are needed.
The libusb.dll is for an experimental usage of libgphoto2, which is currently not used.
