### ISSUE TITLE
Could not claim the USB device when using Canon

### ISSUE THREAD

**Issue by arnozeng** [vividos/RemotePhotoTool#6]
when try to test Canon by 'RemotePhotoToolCmdline.exe -o {2}', but shown "Could not claim the USB device"

![image](https://user-images.githubusercontent.com/64408767/111116589-31671480-85a1-11eb-87a8-d1c9f9c1b820.png)

which's step i miss? how to fix this problem?

**Comment by arnozeng** [comment]
i use this exe program in WINDOWS 10

**Comment by vividos** [comment]
Can you use the camera using the Canon remote program that's installed with the Canon CDs?

**Comment by vividos** [comment]
Ah I see that the program tries to use the libgphoto2 driver. This driver is not usable at the moment, so you have to switch back your Canon camera to use the Windows driver, not the libusb driver to use it.

**Comment by arnozeng** [comment]
canon sdk is work. i switch to windriver, this RemotePhotoToolCmdline.exe program can work in libgphoto2. Thx.  and i try to test gphoto2 lib, but can't work,  show below message.
![image](https://user-images.githubusercontent.com/64408767/111130033-b823ed80-85b1-11eb-80cc-509348371b19.png)

**Comment by arnozeng** [comment]
this error shown from gp_camera_init  step.  
'''
printf ("Creating camera...\n");
	context = gp_context_new();

	gp_context_set_error_func(context, ctx_error_func, NULL);
	gp_context_set_status_func(context, ctx_status_func, NULL);
	

	CHECK (gp_camera_new (&camera));

	/*
	 * Now, initialize the camera (establish a connection).
	 */
	printf ("Initializing camera...\n");
	CHECK (gp_camera_init (camera, context));

'''

**Comment by arnozeng** [comment]
![image](https://user-images.githubusercontent.com/64408767/111132194-02a66980-85b4-11eb-8430-a62b9eb28c79.png)
and i try to run in WpfDotNetCameraControl.exe, it also can't work in libgphoto2.  what's the different of connection between WpfDotNetCameraControl.exe and  RemotePhotoToolCmdline.exe

**Comment by vividos** [comment]
As I said, the libgphoto2 is not usable. WpfDotNetCameraControl.exe is an example how to work with the C# wrapper and should not used by the end user as is. RemotePhotoToolCmdline.exe is a command line tool to do some operations of the normal RemotePhotoTool tool. As you said that using the normal windows driver works, in closing the issue. Please feel free to open another ticket when something with the Windows driver doesn't work. Thank you!
