### ISSUE TITLE
crash happens to 1.6

### ISSUE THREAD

**Issue by colorzircon** [vividos/RemotePhotoTool#8]
Hi friend,

Thank you very much for building such awesome software that works very well with my EOS 750D.

However, a crash happens sometimes. So, could you please release an upgraded version?

Actually, I noticed that you have built version 1.7, but I cannot find the download link.

Best,
Lei

**Comment by vividos** [comment]
I can take a look at the crash if you can provide me with a crash dump file. It should be possible to save the files at crash time in the dialog that is shown.
Thanks!

**Comment by colorzircon** [comment]
![Picture2](https://github.com/vividos/RemotePhotoTool/assets/35207803/f7dd48d3-f285-42dd-a12a-d5dda0cc0017)
![Picture1](https://github.com/vividos/RemotePhotoTool/assets/35207803/cb8698ef-a241-45b9-b615-7c1f5f497816)

I'm sorry I can't find the crash dump file. I saved the screenshot. 
A crash happened when I tried to make a "save to" option, another happened when I clicked the "HDR" button. See the attached images.

Thanks.

**Comment by vividos** [comment]
It seems the app is blocking, not crashed. In this case you can create a dump using task manager, in the details tab find the RemotePhotoTool.exe, right click and select "create dump". The files can get rather large, though.
You can also try the latest CI build if it still has the problem:
https://ci.appveyor.com/project/vividos/remotephototool

**Comment by colorzircon** [comment]
Thanks very much. I will try.

**Comment by vividos** [comment]
Does the new version fix your problem?
